// Caps word
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

// 
#define LSPO_KEYS KC_LSFT,KC_LSFT,KC_8
#define RSPC_KEYS KC_RSFT,KC_LSFT,KC_9

// Auto shift
#define AUTO_SHIFT_TIMEOUT 115
#define AUTO_SHIFT_NO_SETUP
#define AUTO_SHIFT_REPEAT
#define AUTO_SHIFT_NO_AUTO_REPEAT
